## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [3]:
mat1=[[1,2,3],[4,5,6]]
mat2=[[1,2,3],[9,7,8]]

#make lists as matrices  
arr1=np.array(mat1)
arr2=np.array(mat2)

arr1*arr2

array([[ 1,  4,  9],
       [36, 35, 48]])

## Write a NumPy program to compute the determinant of a given square array

In [ ]:
from numpy import linalg as LA    ### select linalg from numpy library

In [13]:
matrix = np.array([[0, 1], [2, 3]])  ### create matrix
np.linalg.det(matrix)

-2.0

## Write a NumPy program to compute the cross product of two given vectors

In [4]:
vect1 = [[1, 0], [0, 1]]
vect2 = [[1, 2], [3, 4]]

cross_mul=np.cross(vect1,vect2) ### built in funcunction
cross_mul

array([ 2, -3])

## Write a NumPy program to compute the condition number of a given matrix

## Write a NumPy program to compute the inverse of a given matrix

In [14]:
mat_inv = np.array([[1,2],[3,4]])

In [18]:
np.linalg.inv(mat_inv)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])